config/routes.rb
Rails.application.routes.draw do

  resources :home, only: [:index, :new, :create]
  root      'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha => true
  
  def headers

    {
      :subject => "Contacting You",
      :to => "michaellindstromportfolio@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @contact = Home.new(params[:home])
  end

  def create
    puts "hello"
    @contact = Home.new(params[:home])
    @contact.request = request
    respond_to do |format|
      if @contact.deliver
        @contact = Home.new
        format.html { render 'index' }
        format.js   { flash.now[:success] = @message = "Thank you for your message. I'll get back to you soon!" }
      else
        format.html { render 'index' }
        format.js   { flash.now[:error] = @message = "Message did not send." }
      end
    end
  end


  private
    def home_params

      params.require(:home).permit(:name, :email, :message)

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_contact_form.html.erb
<%= form_for @contact, :url => home_index_path, :method => :post, :remote => true do |f| %>
    <div class="col-md-8 mx-auto">
        <%= f.label :name %></br>
        <%= f.text_field  :name, required: true, class: "contact-form-text-area form-control" %></br>

        <%= f.label :email %></br>
        <%= f.email_field :email, required: true, class: "contact-form-text-area form-control" %></br>

        <%= f.label :message %></br>
        <%= f.text_area :message, rows: 8, cols: 40, required: true, class: "contact-form-text-area form-control", placeholder: "Send me a message."%></br>

        <div class="hidden">
            <%= f.label :nickname %></br>
            <%= f.text_field :nickname, hint: 'leave this field blank.' %>
        </div>

        <%= f.submit 'Send Message', class: 'btn form-control contact-submit' %>
    </div>
<% end %>

<div class="col-md-6 mx-auto pt-4 mb-4" id="flash-message">
    <div class="hidden">Thanks for Visiting!</div>
    <%= render 'flash' %>
</div>

app/views/home/_flash.html.erb
<% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type} mx-auto mb-0") %>
<% end %>

app/views/home/create.js.erb
// Render flash message
$('#contact').html("<%= j render 'contact_form' %>");
$('#flash-message').html("<%= j render 'flash' %>").delay(2000).animate({"opacity":"0"}, 2000);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Michael Lindstrom</title>
    <%= favicon_link_tag 'logo.png' %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', 'https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="mb-0 stop-scrolling" data-spy="scroll" data-target="#navbar" data-offset="400" id="top">
      <%= render 'shared/header' %>
      <div class="test-holder-div d-flex align-items-center justify-content-center mx-auto">
          <%= image_tag("logo.png", alt: "logo", height: "100px", width: "100px", class: "test-holder-image mx-auto") %>
      </div>
      <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="footer py-2 mt-4">
      <div class="container">
        <div class="mx-auto social_logos d-flex justify-content-center">
            <%= link_to image_tag("githublogo.png", alt: "github", height: '30px', width: '30px'), 'https://github.com/michaellindstromm', class: 'navbar-brand' %>
            <%= link_to image_tag("linkedinlogo.png", alt: "github", height: '20px', width: '20px'), 'https://www.linkedin.com/in/michaelglindstrom', class: 'navbar-brand' %>
        </div>
      </div>
</footer>

app/views/shared/_header.html.erb
<header class="navbar navbar-expand-lg navbar-dark fixed-top transparent-nav" id="navbar">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="brand-holder">
    <a class="smooth-scroll nav-link py-1" href="#top"><%= image_tag("logo.png", alt: "logo", height: '50px', width: '10px', class: 'nav-logo navbar-brand mr-4 hidden') %></a>
  </div>
  <div class="collapse navbar-collapse ml-4" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item text-center">
        <a class="smooth-scroll nav-link" href="#about">About</a>
      </li>
      <li class="nav-item text-center">
        <a class="smooth-scroll nav-link" href="#projects">Projects</a>
      </li>
      <li class="nav-item text-center">
        <a class="smooth-scroll nav-link" href="#contact">Contact</a>
      </li>
    </ul>
  </div>
</header>